// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AlignLyrics(arg1:number,arg2:number):Promise<model.LyricDocument>;

export function ApplyLyricCandidate(arg1:model.LyricSearchCandidate):Promise<model.LyricDocument>;

export function AutoAlignLyrics(arg1:number):Promise<model.LyricCalibrationResult>;

export function ConfigPath():Promise<string>;

export function ConnectAMLL(arg1:string):Promise<void>;

export function ControlPlayback(arg1:string,arg2:number):Promise<void>;

export function DisconnectAMLL():Promise<void>;

export function GetConfig():Promise<model.AppConfig>;

export function GetState():Promise<model.AppSnapshot>;

export function HideWindow():Promise<void>;

export function ImportLyrics(arg1:string):Promise<model.LyricDocument>;

export function MinimizeWindow():Promise<void>;

export function OffsetLyrics(arg1:number):Promise<model.LyricDocument>;

export function Quit():Promise<void>;

export function RestartServices():Promise<void>;

export function RunAITask(arg1:model.AITaskRequest):Promise<model.AITaskResult>;

export function SaveConfig(arg1:model.AppConfig):Promise<void>;

export function SearchLyricCandidates(arg1:string,arg2:string,arg3:string):Promise<Array<model.LyricSearchCandidate>>;

export function SearchLyrics(arg1:string,arg2:string,arg3:string):Promise<model.LyricDocument>;

export function SelectSession(arg1:string):Promise<void>;

export function SendLyricsToAMLL():Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function ShowWindow():Promise<void>;

export function SuggestLyricAlignment(arg1:number):Promise<model.LyricCalibrationSuggestion>;
