// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlignLyrics(arg1, arg2) {
  return window['go']['main']['App']['AlignLyrics'](arg1, arg2);
}

export function ApplyLyricCandidate(arg1) {
  return window['go']['main']['App']['ApplyLyricCandidate'](arg1);
}

export function AutoAlignLyrics(arg1) {
  return window['go']['main']['App']['AutoAlignLyrics'](arg1);
}

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function ConnectAMLL(arg1) {
  return window['go']['main']['App']['ConnectAMLL'](arg1);
}

export function ControlPlayback(arg1, arg2) {
  return window['go']['main']['App']['ControlPlayback'](arg1, arg2);
}

export function DisconnectAMLL() {
  return window['go']['main']['App']['DisconnectAMLL']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportLyrics(arg1) {
  return window['go']['main']['App']['ImportLyrics'](arg1);
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OffsetLyrics(arg1) {
  return window['go']['main']['App']['OffsetLyrics'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RestartServices() {
  return window['go']['main']['App']['RestartServices']();
}

export function RunAITask(arg1) {
  return window['go']['main']['App']['RunAITask'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchLyricCandidates(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchLyricCandidates'](arg1, arg2, arg3);
}

export function SearchLyrics(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchLyrics'](arg1, arg2, arg3);
}

export function SelectSession(arg1) {
  return window['go']['main']['App']['SelectSession'](arg1);
}

export function SendLyricsToAMLL() {
  return window['go']['main']['App']['SendLyricsToAMLL']();
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function SuggestLyricAlignment(arg1) {
  return window['go']['main']['App']['SuggestLyricAlignment'](arg1);
}
